"""Shared artifact and schema specifications for ML4T libraries."""

from .base import (
    ArtifactKind,
    ArtifactProvenance,
    ArtifactSpec,
    ArtifactStorage,
    optional_str,
    serialize_artifact_value,
)
from .io import read_spec_payload, write_spec_payload
from .lifecycle import (
    LIFECYCLE_V1,
    BarPayload,
    CallbackCardinality,
    CallbackExceptionSemantics,
    EventCompletion,
    FundingPayload,
    GapEvidence,
    HistoricalStrategyCompatibilityError,
    InformationField,
    LifecycleContract,
    LifecycleCountError,
    LifecyclePhase,
    LifecyclePhaseSpec,
    LifecycleVersion,
    MarketEvent,
    MarketEventKind,
    MarketEventPayload,
    ProhibitedFieldAccessError,
    QuotePayload,
    TradePayload,
    UnsupportedLifecycleVersionError,
    lifecycle_schema,
    negotiate_lifecycle_version,
    require_historical_strategy_compatibility,
)
from .market_data import (
    FeedSpec,
    MarketDataSchema,
    MarketDataSemantics,
    MarketDataSpec,
    TimestampSemantics,
)

__version__ = "0.1.0"

__all__ = [
    "ArtifactKind",
    "ArtifactProvenance",
    "ArtifactSpec",
    "ArtifactStorage",
    "BarPayload",
    "CallbackCardinality",
    "CallbackExceptionSemantics",
    "EventCompletion",
    "FeedSpec",
    "FundingPayload",
    "GapEvidence",
    "HistoricalStrategyCompatibilityError",
    "InformationField",
    "LIFECYCLE_V1",
    "LifecycleContract",
    "LifecycleCountError",
    "LifecyclePhase",
    "LifecyclePhaseSpec",
    "LifecycleVersion",
    "MarketDataSchema",
    "MarketDataSemantics",
    "MarketDataSpec",
    "MarketEvent",
    "MarketEventKind",
    "MarketEventPayload",
    "ProhibitedFieldAccessError",
    "QuotePayload",
    "TimestampSemantics",
    "TradePayload",
    "UnsupportedLifecycleVersionError",
    "lifecycle_schema",
    "negotiate_lifecycle_version",
    "optional_str",
    "read_spec_payload",
    "require_historical_strategy_compatibility",
    "serialize_artifact_value",
    "write_spec_payload",
]
